// Code generated by protoc-gen-go.
// source: customer/customer.proto
// DO NOT EDIT!

/*
Package customer is a generated protocol buffer package.

It is generated from these files:
	customer/customer.proto

It has these top-level messages:
	ReportRequest
	ReportResponse
	SetConfigRequest
	SetConfigResponse
	GetConfigRequest
	ConfigHistoryItem
	Customer
	Advertiser
	Campaign
	Native
	Creative
	Targeting
*/
package customer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReportRequest struct {
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	FromDate string `protobuf:"bytes,2,opt,name=from_date,json=fromDate" json:"from_date,omitempty"`
	ToDate   string `protobuf:"bytes,3,opt,name=to_date,json=toDate" json:"to_date,omitempty"`
	// Available output formats: Pretty, JSON, CSV[WithNames], TabSeparated[WithNames[AndTypes]], XML (default "Pretty")
	Format string `protobuf:"bytes,4,opt,name=format" json:"format,omitempty"`
}

func (m *ReportRequest) Reset()                    { *m = ReportRequest{} }
func (m *ReportRequest) String() string            { return proto.CompactTextString(m) }
func (*ReportRequest) ProtoMessage()               {}
func (*ReportRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ReportResponse struct {
	Data string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *ReportResponse) Reset()                    { *m = ReportResponse{} }
func (m *ReportResponse) String() string            { return proto.CompactTextString(m) }
func (*ReportResponse) ProtoMessage()               {}
func (*ReportResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SetConfigRequest struct {
	Client *Customer `protobuf:"bytes,1,opt,name=client" json:"client,omitempty"`
}

func (m *SetConfigRequest) Reset()                    { *m = SetConfigRequest{} }
func (m *SetConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*SetConfigRequest) ProtoMessage()               {}
func (*SetConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SetConfigRequest) GetClient() *Customer {
	if m != nil {
		return m.Client
	}
	return nil
}

type SetConfigResponse struct {
	Data string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *SetConfigResponse) Reset()                    { *m = SetConfigResponse{} }
func (m *SetConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*SetConfigResponse) ProtoMessage()               {}
func (*SetConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type GetConfigRequest struct {
}

func (m *GetConfigRequest) Reset()                    { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()               {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ConfigHistoryItem struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Date   string `protobuf:"bytes,2,opt,name=date" json:"date,omitempty"`
	Diff   string `protobuf:"bytes,3,opt,name=diff" json:"diff,omitempty"`
	Author string `protobuf:"bytes,4,opt,name=author" json:"author,omitempty"`
}

func (m *ConfigHistoryItem) Reset()                    { *m = ConfigHistoryItem{} }
func (m *ConfigHistoryItem) String() string            { return proto.CompactTextString(m) }
func (*ConfigHistoryItem) ProtoMessage()               {}
func (*ConfigHistoryItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Customer struct {
	// There should be at least one advertiser in the config.
	Advertisers map[string]*Advertiser `protobuf:"bytes,1,rep,name=advertisers" json:"advertisers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Customer) Reset()                    { *m = Customer{} }
func (m *Customer) String() string            { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()               {}
func (*Customer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Customer) GetAdvertisers() map[string]*Advertiser {
	if m != nil {
		return m.Advertisers
	}
	return nil
}

type Advertiser struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// There should be at least one campaign for each advertiser.
	Campaigns map[string]*Campaign `protobuf:"bytes,2,rep,name=campaigns" json:"campaigns,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// There should be at least one creative for each advertiser.
	Creatives map[string]*Creative `protobuf:"bytes,3,rep,name=creatives" json:"creatives,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Advertiser) Reset()                    { *m = Advertiser{} }
func (m *Advertiser) String() string            { return proto.CompactTextString(m) }
func (*Advertiser) ProtoMessage()               {}
func (*Advertiser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Advertiser) GetCampaigns() map[string]*Campaign {
	if m != nil {
		return m.Campaigns
	}
	return nil
}

func (m *Advertiser) GetCreatives() map[string]*Creative {
	if m != nil {
		return m.Creatives
	}
	return nil
}

type Campaign struct {
	// System extention fields. Do not Edit.
	Id        string   `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	ClientId  string   `protobuf:"bytes,3,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	Name      string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Creatives []string `protobuf:"bytes,4,rep,name=creatives" json:"creatives,omitempty"`
	// IAB content categories of the campaign. Refer to List 5.1 in the openRTB spec.
	// This is sent in the bid response as the "cat" field.
	// This is compared with the "bcat" field in the bid request. If matched - the campaign is not bidded.
	Category []string          `protobuf:"bytes,5,rep,name=category" json:"category,omitempty"`
	Pricing  *Campaign_Pricing `protobuf:"bytes,6,opt,name=pricing" json:"pricing,omitempty"`
	Budget   *Campaign_Budget  `protobuf:"bytes,7,opt,name=budget" json:"budget,omitempty"`
	// Required. If campaign has no targetings, please pass the empty object like {}.
	Targeting *Targeting `protobuf:"bytes,8,opt,name=targeting" json:"targeting,omitempty"`
	// URL of the landing page without get parameters.
	// This is sent to the "adomain" bid response field.
	// The landing page's domain is compared with the "badv" field in the bid request. If matched - the campaign is not bidded.
	LandingPageUrl []string `protobuf:"bytes,9,rep,name=landing_page_url,json=landingPageUrl" json:"landing_page_url,omitempty"`
	// The URL without the protocol prefix (http:// or https://) which will be called on the impression.
	// {RANDOM} macro could be used for cachebusting.
	// Incorrect Ex: http://www.tracker.com/?...
	// Correct Ex: wwww.tracker.com/?...
	// "http://" or "https://" will be added automatically based on the "imp.secure" flag into the bid request.
	// Note: if the impression tracker doesn't have the valid SSL certificate - please populate the "creative.insecure" flag to TRUE to avoid the stats discrepancies
	ImpressionTrackingUrl string `protobuf:"bytes,10,opt,name=impression_tracking_url,json=impressionTrackingUrl" json:"impression_tracking_url,omitempty"`
	// Campaign start datetime in the YYYY-MM-DDThh:mm:ss±hh:mm format.
	// The date could be ommited (Thh:mm:ss±hh:mm format). In that case campaign is started daily at this time.
	StartDate string `protobuf:"bytes,11,opt,name=start_date,json=startDate" json:"start_date,omitempty"`
	// Campaign stop datetime in the YYYY-MM-DDThh:mm:ss±hh:mm format.
	// The date could be ommited (Thh:mm:ss±hh:mm format). In that case campaign is stopped daily at this time.
	StopDate string `protobuf:"bytes,12,opt,name=stop_date,json=stopDate" json:"stop_date,omitempty"`
}

func (m *Campaign) Reset()                    { *m = Campaign{} }
func (m *Campaign) String() string            { return proto.CompactTextString(m) }
func (*Campaign) ProtoMessage()               {}
func (*Campaign) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Campaign) GetPricing() *Campaign_Pricing {
	if m != nil {
		return m.Pricing
	}
	return nil
}

func (m *Campaign) GetBudget() *Campaign_Budget {
	if m != nil {
		return m.Budget
	}
	return nil
}

func (m *Campaign) GetTargeting() *Targeting {
	if m != nil {
		return m.Targeting
	}
	return nil
}

// Required
type Campaign_Pricing struct {
	// This is compared against ortb field "cur" from the bid request,
	// which contains ISO-4217 alpha codes of the currencies, allowed for the bid.
	Currency string `protobuf:"bytes,1,opt,name=currency" json:"currency,omitempty"`
	// This number is sent into the bid response as the bid CPM price.
	Bid float64 `protobuf:"fixed64,2,opt,name=bid" json:"bid,omitempty"`
	// This number divided by 1,000 (CPM) the campaign budget is decreased on the impression.
	Impression float64 `protobuf:"fixed64,3,opt,name=impression" json:"impression,omitempty"`
}

func (m *Campaign_Pricing) Reset()                    { *m = Campaign_Pricing{} }
func (m *Campaign_Pricing) String() string            { return proto.CompactTextString(m) }
func (*Campaign_Pricing) ProtoMessage()               {}
func (*Campaign_Pricing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 0} }

type Campaign_Budget struct {
	// Campaign daily budget limit. Daily budget is reseted every day at midnight by the UTC+3 (Moscow) time zone.
	// Please be carefull: if you set zero daily budget - that means no limit, so the campaign will spend money unstoppable.
	Daily float64 `protobuf:"fixed64,1,opt,name=daily" json:"daily,omitempty"`
}

func (m *Campaign_Budget) Reset()                    { *m = Campaign_Budget{} }
func (m *Campaign_Budget) String() string            { return proto.CompactTextString(m) }
func (*Campaign_Budget) ProtoMessage()               {}
func (*Campaign_Budget) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 1} }

type Native struct {
	Assets []*Native_Asset `protobuf:"bytes,1,rep,name=assets" json:"assets,omitempty"`
}

func (m *Native) Reset()                    { *m = Native{} }
func (m *Native) String() string            { return proto.CompactTextString(m) }
func (*Native) ProtoMessage()               {}
func (*Native) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Native) GetAssets() []*Native_Asset {
	if m != nil {
		return m.Assets
	}
	return nil
}

type Native_Asset struct {
	Title *Native_Asset_Title `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Image *Native_Asset_Image `protobuf:"bytes,2,opt,name=image" json:"image,omitempty"`
}

func (m *Native_Asset) Reset()                    { *m = Native_Asset{} }
func (m *Native_Asset) String() string            { return proto.CompactTextString(m) }
func (*Native_Asset) ProtoMessage()               {}
func (*Native_Asset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 0} }

func (m *Native_Asset) GetTitle() *Native_Asset_Title {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *Native_Asset) GetImage() *Native_Asset_Image {
	if m != nil {
		return m.Image
	}
	return nil
}

type Native_Asset_Title struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (m *Native_Asset_Title) Reset()                    { *m = Native_Asset_Title{} }
func (m *Native_Asset_Title) String() string            { return proto.CompactTextString(m) }
func (*Native_Asset_Title) ProtoMessage()               {}
func (*Native_Asset_Title) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 0, 0} }

type Native_Asset_Image struct {
	Url    string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Width  int64  `protobuf:"varint,2,opt,name=width" json:"width,omitempty"`
	Height int64  `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
}

func (m *Native_Asset_Image) Reset()                    { *m = Native_Asset_Image{} }
func (m *Native_Asset_Image) String() string            { return proto.CompactTextString(m) }
func (*Native_Asset_Image) ProtoMessage()               {}
func (*Native_Asset_Image) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 0, 1} }

type Creative struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Please ignore this field.
	Id string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	// Please ignore this field.
	AdId string `protobuf:"bytes,3,opt,name=ad_id,json=adId" json:"ad_id,omitempty"`
	// Please populate this flag to TRUE in case the creative code has the "http://" requests
	// or impression_tracking_url doesn't have the valid SSL certificate.
	Insecure bool `protobuf:"varint,4,opt,name=insecure" json:"insecure,omitempty"`
	// Available creative types: "3rd_party_banner", "video".
	Type string `protobuf:"bytes,5,opt,name=type" json:"type,omitempty"`
	// URL the user is sent to on click. Should contains the protocol (http:// or https://).
	// This is required for the creatives which should be rotated in the Google Ad Exchange.
	ClickUrl string         `protobuf:"bytes,6,opt,name=click_url,json=clickUrl" json:"click_url,omitempty"`
	Size     *Creative_Size `protobuf:"bytes,7,opt,name=size" json:"size,omitempty"`
	// Creative's html snippet. Should contains valid html code.
	// This field could contains the following macros:
	// {CLICK_URL} will be resolved to the click URL handler.
	// {CLICK_URL_ESC} will be resolved to the escaped click URL handler.
	// {PUB_ID} will be resolved to the publisher id.
	// Note: either {CLICK_URL} or {CLICK_URL_ESC} is required for the creatives which should be rotated in the Google Ad Exchange.
	HtmlContent string `protobuf:"bytes,8,opt,name=html_content,json=htmlContent" json:"html_content,omitempty"`
	// Video ad duration in seconds. Required for the creative type "video".
	// This is compared with the "video.minduration" and "video.maxduration" fields in the bid request.
	// Creative's duration should be between these values to be eligible for bid.
	Duration int64 `protobuf:"varint,9,opt,name=duration" json:"duration,omitempty"`
	// Creative's MIME type. This is compared with the "banner.mimes" field in the bid request.
	// If no matches - creative is not eligible for bid.
	Mimes []string `protobuf:"bytes,10,rep,name=mimes" json:"mimes,omitempty"`
	// Supported video protocols. Required for the creative type "video". Refer to List 5.8 in the Open RTB spec.
	// This is compared with the "video.protocols" field in the bid request.
	// If no matches - creative is not eligible for bid.
	Protocols []string `protobuf:"bytes,11,rep,name=protocols" json:"protocols,omitempty"`
	// The URL which returns the valid VAST XML.
	// Required for the creative type "video".
	VastUrl string  `protobuf:"bytes,12,opt,name=vast_url,json=vastUrl" json:"vast_url,omitempty"`
	Native  *Native `protobuf:"bytes,13,opt,name=native" json:"native,omitempty"`
}

func (m *Creative) Reset()                    { *m = Creative{} }
func (m *Creative) String() string            { return proto.CompactTextString(m) }
func (*Creative) ProtoMessage()               {}
func (*Creative) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Creative) GetSize() *Creative_Size {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *Creative) GetNative() *Native {
	if m != nil {
		return m.Native
	}
	return nil
}

type Creative_Size struct {
	Width  int64 `protobuf:"varint,1,opt,name=width" json:"width,omitempty"`
	Height int64 `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
}

func (m *Creative_Size) Reset()                    { *m = Creative_Size{} }
func (m *Creative_Size) String() string            { return proto.CompactTextString(m) }
func (*Creative_Size) ProtoMessage()               {}
func (*Creative_Size) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10, 0} }

type Targeting struct {
	Geo *Targeting_Geo  `protobuf:"bytes,1,opt,name=geo" json:"geo,omitempty"`
	Os  []*Targeting_OS `protobuf:"bytes,2,rep,name=os" json:"os,omitempty"`
	// The minimum delay between any two impressions for the single user in the one ad network in seconds.
	// Works by "user.id" field in the bid request.
	Frequency int64                `protobuf:"varint,3,opt,name=frequency" json:"frequency,omitempty"`
	UserAgent *Targeting_UserAgent `protobuf:"bytes,4,opt,name=user_agent,json=userAgent" json:"user_agent,omitempty"`
	// Carrier or ISP as it's declared in the "device.carrier" field in the bid request.
	Carrier *Targeting_ListMatch `protobuf:"bytes,5,opt,name=carrier" json:"carrier,omitempty"`
	// IAB content categories as it's declared in the "site.cat" or "app.cat" fields in the bid request.
	Cat *Targeting_ListMatch `protobuf:"bytes,6,opt,name=cat" json:"cat,omitempty"`
	// The general type of device as it's declared in the "device.devicetype" field in the bid request.
	// Refer to List 5.17 in the Open RTB spec.
	DeviceType *Targeting_ListMatch `protobuf:"bytes,7,opt,name=device_type,json=deviceType" json:"device_type,omitempty"`
	// Site's domain is extracted from the "site.page" field in the bid request and compared with the populated list.
	Domain *Targeting_ListMatch `protobuf:"bytes,8,opt,name=domain" json:"domain,omitempty"`
	// Works by the "publisher.id" field in the bid request.
	Publisher *Targeting_ListMatch `protobuf:"bytes,9,opt,name=publisher" json:"publisher,omitempty"`
	// Works by the "ext.ssp" field in the bid request.
	Ssp    *Targeting_ListMatch `protobuf:"bytes,10,opt,name=ssp" json:"ssp,omitempty"`
	Google *Targeting_Google    `protobuf:"bytes,11,opt,name=google" json:"google,omitempty"`
	// Connected ad networks targeting. Please ask your account manager to obtain the available networks list.
	Network *Targeting_ListMatch `protobuf:"bytes,12,opt,name=network" json:"network,omitempty"`
	Ip      *Targeting_ListMatch `protobuf:"bytes,13,opt,name=ip" json:"ip,omitempty"`
}

func (m *Targeting) Reset()                    { *m = Targeting{} }
func (m *Targeting) String() string            { return proto.CompactTextString(m) }
func (*Targeting) ProtoMessage()               {}
func (*Targeting) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Targeting) GetGeo() *Targeting_Geo {
	if m != nil {
		return m.Geo
	}
	return nil
}

func (m *Targeting) GetOs() []*Targeting_OS {
	if m != nil {
		return m.Os
	}
	return nil
}

func (m *Targeting) GetUserAgent() *Targeting_UserAgent {
	if m != nil {
		return m.UserAgent
	}
	return nil
}

func (m *Targeting) GetCarrier() *Targeting_ListMatch {
	if m != nil {
		return m.Carrier
	}
	return nil
}

func (m *Targeting) GetCat() *Targeting_ListMatch {
	if m != nil {
		return m.Cat
	}
	return nil
}

func (m *Targeting) GetDeviceType() *Targeting_ListMatch {
	if m != nil {
		return m.DeviceType
	}
	return nil
}

func (m *Targeting) GetDomain() *Targeting_ListMatch {
	if m != nil {
		return m.Domain
	}
	return nil
}

func (m *Targeting) GetPublisher() *Targeting_ListMatch {
	if m != nil {
		return m.Publisher
	}
	return nil
}

func (m *Targeting) GetSsp() *Targeting_ListMatch {
	if m != nil {
		return m.Ssp
	}
	return nil
}

func (m *Targeting) GetGoogle() *Targeting_Google {
	if m != nil {
		return m.Google
	}
	return nil
}

func (m *Targeting) GetNetwork() *Targeting_ListMatch {
	if m != nil {
		return m.Network
	}
	return nil
}

func (m *Targeting) GetIp() *Targeting_ListMatch {
	if m != nil {
		return m.Ip
	}
	return nil
}

// Required for campaigns, which should be served in the Google Ad Exchange
type Targeting_Google struct {
	BillingId string `protobuf:"bytes,1,opt,name=billing_id,json=billingId" json:"billing_id,omitempty"`
}

func (m *Targeting_Google) Reset()                    { *m = Targeting_Google{} }
func (m *Targeting_Google) String() string            { return proto.CompactTextString(m) }
func (*Targeting_Google) ProtoMessage()               {}
func (*Targeting_Google) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11, 0} }

type Targeting_Geo struct {
	// Country code as it's populated in the "device.geo.country" field.
	Country *Targeting_ListMatch `protobuf:"bytes,1,opt,name=country" json:"country,omitempty"`
	// City as it's populated in the "device.geo.city" field.
	City *Targeting_ListMatch `protobuf:"bytes,2,opt,name=city" json:"city,omitempty"`
}

func (m *Targeting_Geo) Reset()                    { *m = Targeting_Geo{} }
func (m *Targeting_Geo) String() string            { return proto.CompactTextString(m) }
func (*Targeting_Geo) ProtoMessage()               {}
func (*Targeting_Geo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11, 1} }

func (m *Targeting_Geo) GetCountry() *Targeting_ListMatch {
	if m != nil {
		return m.Country
	}
	return nil
}

func (m *Targeting_Geo) GetCity() *Targeting_ListMatch {
	if m != nil {
		return m.City
	}
	return nil
}

type Targeting_OS struct {
	// Device operating system as it's declared in the "device.os" field in the bid request.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Device operating system version as it's declared in the "device.osv" field in the bid request.
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (m *Targeting_OS) Reset()                    { *m = Targeting_OS{} }
func (m *Targeting_OS) String() string            { return proto.CompactTextString(m) }
func (*Targeting_OS) ProtoMessage()               {}
func (*Targeting_OS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11, 2} }

type Targeting_UserAgent struct {
	// Available browser names: "Opera", "Edge", "Chrome", "Safari", "Internet Explorer"
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// If the flag is set to TRUE, the only mobile versions of the browser's user agent are passed.
	Mobile bool `protobuf:"varint,2,opt,name=mobile" json:"mobile,omitempty"`
}

func (m *Targeting_UserAgent) Reset()                    { *m = Targeting_UserAgent{} }
func (m *Targeting_UserAgent) String() string            { return proto.CompactTextString(m) }
func (*Targeting_UserAgent) ProtoMessage()               {}
func (*Targeting_UserAgent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11, 3} }

type Targeting_ListMatch struct {
	Include bool     `protobuf:"varint,1,opt,name=include" json:"include,omitempty"`
	List    []string `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
}

func (m *Targeting_ListMatch) Reset()                    { *m = Targeting_ListMatch{} }
func (m *Targeting_ListMatch) String() string            { return proto.CompactTextString(m) }
func (*Targeting_ListMatch) ProtoMessage()               {}
func (*Targeting_ListMatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11, 4} }

func init() {
	proto.RegisterType((*ReportRequest)(nil), "customer.ReportRequest")
	proto.RegisterType((*ReportResponse)(nil), "customer.ReportResponse")
	proto.RegisterType((*SetConfigRequest)(nil), "customer.SetConfigRequest")
	proto.RegisterType((*SetConfigResponse)(nil), "customer.SetConfigResponse")
	proto.RegisterType((*GetConfigRequest)(nil), "customer.GetConfigRequest")
	proto.RegisterType((*ConfigHistoryItem)(nil), "customer.ConfigHistoryItem")
	proto.RegisterType((*Customer)(nil), "customer.Customer")
	proto.RegisterType((*Advertiser)(nil), "customer.Advertiser")
	proto.RegisterType((*Campaign)(nil), "customer.Campaign")
	proto.RegisterType((*Campaign_Pricing)(nil), "customer.Campaign.Pricing")
	proto.RegisterType((*Campaign_Budget)(nil), "customer.Campaign.Budget")
	proto.RegisterType((*Native)(nil), "customer.Native")
	proto.RegisterType((*Native_Asset)(nil), "customer.Native.Asset")
	proto.RegisterType((*Native_Asset_Title)(nil), "customer.Native.Asset.Title")
	proto.RegisterType((*Native_Asset_Image)(nil), "customer.Native.Asset.Image")
	proto.RegisterType((*Creative)(nil), "customer.Creative")
	proto.RegisterType((*Creative_Size)(nil), "customer.Creative.Size")
	proto.RegisterType((*Targeting)(nil), "customer.Targeting")
	proto.RegisterType((*Targeting_Google)(nil), "customer.Targeting.Google")
	proto.RegisterType((*Targeting_Geo)(nil), "customer.Targeting.Geo")
	proto.RegisterType((*Targeting_OS)(nil), "customer.Targeting.OS")
	proto.RegisterType((*Targeting_UserAgent)(nil), "customer.Targeting.UserAgent")
	proto.RegisterType((*Targeting_ListMatch)(nil), "customer.Targeting.ListMatch")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for API service

type APIClient interface {
	// Return clients metricks for the specified client ID with breakdown by Campaign ID.
	Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*Customer, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	out := new(ReportResponse)
	err := grpc.Invoke(ctx, "/customer.API/Report", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error) {
	out := new(SetConfigResponse)
	err := grpc.Invoke(ctx, "/customer.API/SetConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*Customer, error) {
	out := new(Customer)
	err := grpc.Invoke(ctx, "/customer.API/GetConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for API service

type APIServer interface {
	// Return clients metricks for the specified client ID with breakdown by Campaign ID.
	Report(context.Context, *ReportRequest) (*ReportResponse, error)
	SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error)
	GetConfig(context.Context, *GetConfigRequest) (*Customer, error)
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.API/Report",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Report(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.API/SetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.API/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "customer.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Report",
			Handler:    _API_Report_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _API_SetConfig_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _API_GetConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("customer/customer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x57, 0x6b, 0x72, 0x1b, 0x45,
	0x10, 0x8e, 0x5e, 0x2b, 0x6d, 0x2b, 0x71, 0x39, 0x93, 0x10, 0x2b, 0x9b, 0x47, 0x81, 0xa0, 0x88,
	0x81, 0x42, 0x29, 0x4c, 0x20, 0xbc, 0x92, 0x2a, 0x63, 0x82, 0x71, 0x15, 0x10, 0xd7, 0xd8, 0x29,
	0x7e, 0xaa, 0xd6, 0xbb, 0x63, 0x69, 0xca, 0xfb, 0x50, 0x66, 0x67, 0x1d, 0x94, 0x53, 0x70, 0x0b,
	0x7e, 0x70, 0x01, 0xce, 0x00, 0xbf, 0x39, 0x04, 0xb7, 0xa0, 0xe7, 0xb1, 0xbb, 0x92, 0xbc, 0x89,
	0xc2, 0xbf, 0xe9, 0xee, 0xaf, 0x7b, 0x7a, 0x7a, 0xbe, 0xee, 0xd9, 0x85, 0xad, 0x20, 0xcf, 0x64,
	0x1a, 0x33, 0x71, 0xbf, 0x58, 0x8c, 0x66, 0x22, 0x95, 0x29, 0xe9, 0x15, 0xf2, 0xf0, 0x25, 0x5c,
	0xa1, 0x6c, 0x96, 0x0a, 0x49, 0xd9, 0xf3, 0x9c, 0x65, 0x92, 0xdc, 0x02, 0x37, 0x88, 0x38, 0x4b,
	0xe4, 0x98, 0x87, 0x83, 0xc6, 0xdb, 0x8d, 0x6d, 0x97, 0xf6, 0x8c, 0xe2, 0x20, 0x54, 0xc6, 0x53,
	0x91, 0xc6, 0xe3, 0xd0, 0x97, 0x6c, 0xd0, 0x34, 0x46, 0xa5, 0xf8, 0x0e, 0x65, 0xb2, 0x05, 0x5d,
	0x99, 0x1a, 0x53, 0x4b, 0x9b, 0x1c, 0x99, 0x6a, 0xc3, 0x0d, 0x70, 0x4e, 0x53, 0x11, 0xfb, 0x72,
	0xd0, 0x36, 0x7a, 0x23, 0x0d, 0xdf, 0x83, 0x8d, 0x62, 0xef, 0x6c, 0x96, 0x26, 0x19, 0x23, 0x04,
	0xda, 0xe8, 0xef, 0xdb, 0x7d, 0xf5, 0x7a, 0xf8, 0x18, 0x36, 0x8f, 0x98, 0xdc, 0x4b, 0x93, 0x53,
	0x3e, 0x29, 0x92, 0xfc, 0x10, 0x1c, 0x93, 0x93, 0x46, 0xf6, 0x77, 0xc8, 0xa8, 0x3c, 0xe0, 0x9e,
	0x5d, 0x50, 0x8b, 0x18, 0xde, 0x83, 0xab, 0x0b, 0xfe, 0xaf, 0xd9, 0x88, 0xc0, 0xe6, 0xfe, 0xca,
	0x46, 0xc3, 0x00, 0xae, 0x1a, 0xc5, 0x0f, 0x1c, 0xc3, 0x8a, 0xf9, 0x81, 0x64, 0x31, 0xd9, 0x80,
	0x66, 0x59, 0x1b, 0x5c, 0xd9, 0x60, 0x45, 0x41, 0xf4, 0x5a, 0xeb, 0xf8, 0xe9, 0xa9, 0xad, 0x84,
	0x5e, 0xab, 0x3a, 0xf8, 0xb9, 0x9c, 0xa6, 0xa2, 0xa8, 0x83, 0x91, 0x86, 0xbf, 0x37, 0xa0, 0x57,
	0xa4, 0x4d, 0x9e, 0x40, 0xdf, 0x0f, 0xcf, 0x99, 0x90, 0x3c, 0x63, 0x22, 0xc3, 0x5d, 0x5a, 0x78,
	0xbe, 0x77, 0x2f, 0x9e, 0x6f, 0xb4, 0x5b, 0xa1, 0x9e, 0x24, 0x52, 0xcc, 0xe9, 0xa2, 0x9f, 0x77,
	0x0c, 0x9b, 0xab, 0x00, 0xb2, 0x09, 0xad, 0x33, 0x36, 0xb7, 0x89, 0xab, 0x25, 0xd6, 0xb1, 0x73,
	0xee, 0x47, 0xb9, 0x49, 0xbd, 0xbf, 0x73, 0xbd, 0xda, 0xa6, 0x72, 0xa6, 0x06, 0xf2, 0x55, 0xf3,
	0x8b, 0xc6, 0xf0, 0xaf, 0x26, 0x40, 0x65, 0x51, 0x87, 0x4c, 0xfc, 0x98, 0x15, 0x55, 0x54, 0x6b,
	0xb2, 0x8b, 0xfc, 0xf1, 0xe3, 0x99, 0xcf, 0x27, 0x49, 0x86, 0x61, 0x57, 0xb2, 0xaf, 0x9c, 0x47,
	0x7b, 0x05, 0xca, 0x64, 0x5f, 0x79, 0xe9, 0x10, 0x82, 0xf9, 0x92, 0x9f, 0xb3, 0x0c, 0x0b, 0xf8,
	0x9a, 0x10, 0x05, 0xaa, 0x08, 0x51, 0xc8, 0xde, 0x21, 0x6c, 0x2c, 0xc7, 0xaf, 0x39, 0xfc, 0xf6,
	0xf2, 0xe1, 0x17, 0x39, 0x64, 0x5d, 0x17, 0x8e, 0xae, 0x23, 0x2e, 0x6d, 0xf7, 0xff, 0x22, 0x5a,
	0xd7, 0xc5, 0x62, 0xfe, 0xd9, 0xc6, 0x6b, 0xb7, 0x3b, 0x59, 0x4e, 0x35, 0x4b, 0x4e, 0x2d, 0xb5,
	0x61, 0x6b, 0xa5, 0x0d, 0xeb, 0xea, 0x7e, 0x7b, 0xb1, 0x68, 0x6d, 0x2c, 0x9a, 0xbb, 0x50, 0x0f,
	0xe2, 0x41, 0x2f, 0x40, 0x5a, 0x4e, 0x90, 0xc2, 0x83, 0x8e, 0x36, 0x96, 0x32, 0x79, 0x00, 0xdd,
	0x99, 0xe0, 0x01, 0x4f, 0x26, 0x03, 0x47, 0xe7, 0xed, 0x5d, 0xac, 0xc4, 0xe8, 0xd0, 0x20, 0x68,
	0x01, 0x25, 0x9f, 0x80, 0x73, 0x92, 0x87, 0x13, 0x26, 0x07, 0x5d, 0xed, 0x74, 0xb3, 0xc6, 0xe9,
	0x5b, 0x0d, 0xa0, 0x16, 0x88, 0x2e, 0xae, 0xf4, 0x05, 0xae, 0xd4, 0x56, 0x3d, 0xed, 0x75, 0xad,
	0xf2, 0x3a, 0x2e, 0x4c, 0xb4, 0x42, 0x61, 0x45, 0x37, 0x23, 0x3f, 0x09, 0x71, 0x39, 0x9e, 0xf9,
	0x13, 0x36, 0xce, 0x45, 0x34, 0x70, 0x75, 0xfe, 0x1b, 0x56, 0x7f, 0x88, 0xea, 0x67, 0x22, 0x22,
	0x9f, 0xc3, 0x16, 0x8f, 0x67, 0x82, 0x65, 0x19, 0x4f, 0x93, 0xb1, 0x14, 0x7e, 0x70, 0xa6, 0xbc,
	0x94, 0x03, 0xe8, 0x32, 0xbd, 0x55, 0x99, 0x8f, 0xad, 0x55, 0xf9, 0xdd, 0x01, 0xc8, 0x70, 0x3f,
	0x69, 0x06, 0x57, 0x5f, 0x43, 0x5d, 0xad, 0xd1, 0xb3, 0x0b, 0xef, 0x01, 0xf3, 0x9b, 0x19, 0xeb,
	0x65, 0x73, 0x0f, 0x4a, 0xa1, 0x8c, 0xde, 0x2f, 0xd0, 0xb5, 0x75, 0xd1, 0x05, 0xce, 0x85, 0x60,
	0x49, 0x30, 0x2f, 0xa7, 0xa6, 0x95, 0x15, 0x51, 0x4e, 0xec, 0xe5, 0x36, 0xa8, 0x5a, 0x92, 0xbb,
	0x00, 0x55, 0x36, 0xfa, 0x7a, 0x1b, 0x74, 0x41, 0xe3, 0xdd, 0x05, 0xc7, 0xd4, 0x8e, 0x5c, 0x87,
	0x4e, 0xe8, 0xf3, 0xc8, 0x04, 0x6d, 0x50, 0x23, 0x0c, 0x7f, 0x6b, 0x82, 0xf3, 0xb3, 0xbe, 0x5a,
	0x32, 0xc2, 0xa1, 0x92, 0x65, 0x4c, 0x16, 0xa3, 0xe2, 0x46, 0x55, 0x51, 0x83, 0x18, 0xed, 0x2a,
	0x33, 0xb5, 0x28, 0xef, 0x9f, 0x06, 0x74, 0xb4, 0x86, 0xec, 0x40, 0x47, 0x72, 0x19, 0x31, 0x3b,
	0x43, 0x6f, 0xd7, 0x3b, 0x8e, 0x8e, 0x15, 0x86, 0x1a, 0xa8, 0xf2, 0xe1, 0x31, 0x56, 0xdc, 0x32,
	0xfc, 0x55, 0x3e, 0x07, 0x0a, 0x43, 0x0d, 0xd4, 0xbb, 0x05, 0x1d, 0x1d, 0x43, 0xd1, 0x56, 0xb2,
	0x5f, 0x65, 0x41, 0x5b, 0xb5, 0xf6, 0xf6, 0xa1, 0xa3, 0xc1, 0xaa, 0x48, 0xea, 0xae, 0x6c, 0x37,
	0xe1, 0x52, 0x1d, 0xfd, 0x05, 0x0f, 0xe5, 0x54, 0xef, 0xd5, 0xa2, 0x46, 0x50, 0x43, 0x74, 0xca,
	0xf8, 0x64, 0x2a, 0x75, 0xd9, 0x5a, 0xd4, 0x4a, 0xc3, 0x3f, 0x5a, 0xd8, 0x4d, 0x96, 0xef, 0xb5,
	0x0d, 0xb2, 0xda, 0x61, 0xd7, 0xa0, 0xe3, 0x87, 0x55, 0x77, 0xb5, 0xfd, 0x10, 0x3b, 0x0b, 0xaf,
	0x91, 0xe3, 0xfb, 0x80, 0x57, 0xc7, 0xf4, 0x90, 0xee, 0xd1, 0x52, 0xd6, 0xe9, 0xcf, 0x67, 0x0c,
	0xfb, 0xc7, 0xa4, 0x8f, 0x6b, 0xdb, 0xa6, 0xc1, 0x99, 0xe6, 0x99, 0x53, 0xb6, 0x69, 0x70, 0xa6,
	0xa8, 0xf5, 0x11, 0xb4, 0x33, 0xfe, 0x92, 0xd9, 0x06, 0xd9, 0xba, 0x38, 0x0d, 0x46, 0x47, 0x68,
	0xa6, 0x1a, 0x44, 0xde, 0x81, 0xcb, 0x53, 0x19, 0x47, 0xe3, 0x20, 0x4d, 0xa4, 0x7a, 0xd8, 0x7a,
	0x3a, 0x58, 0x5f, 0xe9, 0xf6, 0x8c, 0x4a, 0x25, 0x17, 0xe6, 0x02, 0x3d, 0x91, 0x33, 0xae, 0x3e,
	0x7c, 0x29, 0xab, 0x62, 0xc5, 0x3c, 0xc6, 0xd6, 0x07, 0xdd, 0x1d, 0x46, 0x50, 0x43, 0x41, 0x3f,
	0xf8, 0x41, 0x1a, 0x65, 0xc8, 0x6d, 0x3d, 0x14, 0x4a, 0x05, 0xb9, 0x09, 0xbd, 0x73, 0x3f, 0x93,
	0x3a, 0x77, 0x43, 0xed, 0xae, 0x92, 0x55, 0xea, 0xdb, 0xe0, 0x24, 0x3a, 0xc5, 0xc1, 0x15, 0x9d,
	0xfc, 0xe6, 0xea, 0x45, 0x53, 0x6b, 0xf7, 0x1e, 0x40, 0x5b, 0x9d, 0xa2, 0xba, 0xad, 0x46, 0xfd,
	0x6d, 0x35, 0x97, 0x6e, 0xeb, 0xdf, 0x2e, 0xb8, 0x65, 0xc3, 0x93, 0x0f, 0xa0, 0x35, 0x61, 0xa9,
	0xe5, 0xe1, 0x56, 0xcd, 0x48, 0x18, 0xed, 0xb3, 0x94, 0x2a, 0x0c, 0x79, 0x1f, 0x9a, 0x69, 0xf1,
	0xae, 0xdc, 0xa8, 0x43, 0x3e, 0x3d, 0xa2, 0x88, 0x50, 0x27, 0x3f, 0x15, 0xea, 0x11, 0x57, 0x0d,
	0x69, 0x98, 0x52, 0x29, 0xc8, 0x37, 0x00, 0x39, 0x3e, 0x20, 0x63, 0x24, 0x5e, 0x62, 0xbe, 0x4a,
	0xfa, 0x3b, 0x77, 0xea, 0xa2, 0x3d, 0x43, 0xd4, 0xae, 0x02, 0x51, 0x37, 0x2f, 0x96, 0xe4, 0x21,
	0x74, 0x03, 0x5f, 0x08, 0xce, 0x84, 0xe6, 0xc2, 0x2b, 0x5c, 0x7f, 0xc4, 0x2f, 0x86, 0x9f, 0x7c,
	0x19, 0x4c, 0x69, 0x81, 0x26, 0xf7, 0xa1, 0x85, 0x53, 0xd7, 0x4e, 0xd9, 0x35, 0x4e, 0x0a, 0x49,
	0x1e, 0x43, 0x3f, 0x64, 0xe7, 0x3c, 0x60, 0x63, 0xcd, 0xbc, 0xee, 0x9b, 0x38, 0x82, 0xf1, 0x38,
	0x56, 0xf4, 0xfc, 0x0c, 0x9c, 0x30, 0x8d, 0x7d, 0x9e, 0xd8, 0x71, 0xbb, 0xc6, 0xd5, 0x82, 0xc9,
	0xd7, 0x48, 0x9b, 0xfc, 0x24, 0xe2, 0xd9, 0x14, 0x8f, 0xe8, 0xbe, 0x89, 0x67, 0x85, 0x57, 0x87,
	0xcc, 0xb2, 0x99, 0x1e, 0xba, 0xeb, 0x0f, 0x89, 0x48, 0x9c, 0x29, 0xce, 0x24, 0x4d, 0x27, 0x91,
	0x99, 0xbe, 0x4b, 0xcf, 0xcf, 0x02, 0x01, 0x34, 0x82, 0x5a, 0xa4, 0xba, 0x82, 0x84, 0xc9, 0x17,
	0xa9, 0x38, 0xd3, 0xcc, 0x5d, 0x7f, 0x05, 0x16, 0x4d, 0x3e, 0xc6, 0x29, 0x30, 0xb3, 0xa4, 0x5e,
	0xe3, 0x83, 0x40, 0xef, 0x1e, 0x38, 0x66, 0x67, 0xf5, 0x4e, 0x9c, 0xf0, 0x28, 0x52, 0x6f, 0x4a,
	0xf9, 0xf1, 0xe7, 0x5a, 0xcd, 0x41, 0xe8, 0x3d, 0x87, 0x16, 0x72, 0x54, 0x53, 0x23, 0xcd, 0xd5,
	0xe7, 0x81, 0x65, 0xf3, 0x5a, 0x6a, 0x18, 0x34, 0xbe, 0x8d, 0xed, 0x80, 0xcb, 0xb9, 0x9d, 0xab,
	0x6b, 0xbc, 0x34, 0xd4, 0xdb, 0x81, 0xe6, 0xd3, 0xa3, 0xda, 0x51, 0x37, 0x80, 0x2e, 0x7e, 0x23,
	0xe9, 0xb7, 0xa5, 0x69, 0xfb, 0xda, 0x88, 0xde, 0x43, 0x70, 0x4b, 0x4a, 0xd7, 0xba, 0x62, 0xc3,
	0xc6, 0x29, 0x1e, 0xcb, 0x4c, 0xf8, 0x1e, 0xb5, 0x92, 0xf7, 0x25, 0xb8, 0xe5, 0xfe, 0x2a, 0x3e,
	0x4f, 0x82, 0x28, 0x0f, 0x8d, 0x6f, 0x8f, 0x16, 0xa2, 0x0a, 0x89, 0x34, 0x90, 0xba, 0x41, 0x31,
	0xa4, 0x5a, 0xef, 0xfc, 0xdd, 0x80, 0xd6, 0xee, 0xe1, 0x01, 0x79, 0x04, 0x8e, 0xf9, 0xdc, 0x27,
	0x0b, 0x2d, 0xbe, 0xf4, 0xf3, 0xe1, 0x0d, 0x2e, 0x1a, 0xcc, 0x07, 0xfb, 0xf0, 0x12, 0xf9, 0x1e,
	0xdc, 0xf2, 0x3b, 0x9e, 0x2c, 0x70, 0x64, 0xf5, 0xe7, 0xc0, 0xbb, 0x55, 0x6b, 0x2b, 0xe3, 0x3c,
	0x02, 0x77, 0xbf, 0x2e, 0xce, 0xea, 0xb7, 0xbf, 0x57, 0xf3, 0x53, 0x31, 0xbc, 0x74, 0xe2, 0xe8,
	0xf9, 0xf9, 0xe9, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4d, 0xf4, 0x94, 0x2d, 0x5c, 0x0d, 0x00,
	0x00,
}
